### ISSUE TITLE
How to create the proxy

### ISSUE THREAD

**Issue by resuarez** [nicholas-gh/alexa-skill-kit-python-play-stream#1]
I am interested in used your code to create the local skill for Alexa.

If I am ok, I have to replace the xxxx for my premium key in this line
`listen_key = 'xxxxxxxxx'`

But, I am not sure how to create the proxy for the https.  Please, could you give me some help in that?
```
# we proxy via cloudfront to make an HTTPS server, as AudioPlayer requires HTTPS
domain = 'xxxxxx.cloudfront.net'
```

Thank you in advance.

**Comment by nicholas-gh** [comment]
This is what I set in [AWS CloudFront](https://aws.amazon.com/cloudfront/)

Name | Setting
---------- | --------
Delivery Method | Web
Cookie Logging | Off
Distribution Status | Deployed
Price Class | Use Only US, Canada and Europe
AWS WAF Web ACL | -
State| Enabled
Alternate Domain Names (CNAMEs)| -
SSL Certificate| Default CloudFront Certificate (*.cloudfront.net)
Custom SSL Client Support| -
Supported HTTP Versions| HTTP/2, HTTP/1.1, HTTP/1.0
IPv6| Disabled
Default Root Object |-

and then an Origin

Name | Setting
---------- | --------
Origin Domain Name | prem4.di.fm
Origin Path | 
Origin ID | Custom-prem4.di.fm
Origin SSL Protocols | TLSv1.2TLSv1.1TLSv1
Origin Protocol Policy | HTTP Only
HTTP Port | 80

and Behaviours

Name | Setting
---------- | --------
Path Pattern | Default (*)
Origin | Custom-prem4.di.fm
Viewer Protocol Policy | HTTPS Only
Allowed HTTP Methods | GET, HEAD
Cached HTTP Methods | GET, HEAD (Cached by default)
Forward Headers | All
Forward Cookies | All
Query String Forwarding and Caching | Forward all, cache based on all
Smooth Streaming | No
Restrict Viewer Access | No
Compress Objects Automatically | No

**Comment by resuarez** [comment]
Great, thank you
